#!/usr/bin/env python
# -*- coding: utf-8 -*-

import sys

__author__ = "Rohit Saluja"
__copyright__ = "Copyright © 2018"
__license__ = "MIT"
__version__ = "1.0.0"
__maintainer__ = "ROhit Saluja"
__email__ = "rohit04saluja@protonmail.com"
__status__ = "Production"

def show_help () :
    print "\x1b[0;30;47mUsage:\x1b[0m"
    print "bits <field-width> [<field-width> ...]"
    print "\n\x1b[0;30;47mExample:\x1b[0m"
    print "bits 1 6 9 4"
    print "0x47298"
    print "\x1b[0;36;40mDecimal\x1b[0m | 0     35       297    8"
    print "\x1b[0;36;40mBinary \x1b[0m | 0 100011 100101001 1000"
    print "\x1b[0;36;40mHex    \x1b[0m | 0     23       129    8"

pttrn = list()

def display (b, d, h) :
    dout = "\x1b[0;36;40mDecimal\x1b[0m | "
    bout = "\x1b[0;36;40mBinary \x1b[0m | "
    hout = "\x1b[0;36;40mHex    \x1b[0m | "
    for i in range(0, len(pttrn)) :
        dout += str(d[i]).rjust(pttrn[i]) + " "
        bout += str(b[i]).rjust(pttrn[i]) + " "
        hout += str(h[i]).rjust(pttrn[i]) + " "
    print dout
    print bout
    print hout

if len(sys.argv) > 2:
    for i in range (1, len(sys.argv)) :
        pttrn.append(int(sys.argv[i]))
else :
    show_help()
    sys.exit(0);

try:
    while True :
        in_str = raw_input("")[2:]
        if (len(in_str)*4 < sum(pttrn)) :
            print "The input number is smaller than the expected"
            continue
        in_str = bin(int(in_str, 16))[2:].zfill(len(in_str)*4)
        binary = list()
        decimal = list()
        hexa = list()
        ref = 0
        for p in pttrn :
            binary.append(in_str[ref:ref+p])
            decimal.append(int(in_str[ref:ref+p], 2))
            hexa.append(hex(int(in_str[ref:ref+p], 2))[2:])
            ref += p
        display(binary, decimal, hexa)
except:
    sys.exit(0)
